version: '2'
services:
  welder:
    #TODO WELDER_SERVER_NAME
    container_name: "welder"
    image: "${WELDER_DOCKER_IMAGE}"
    network_mode: host
    restart: always
    environment:
      # needed to disable auth
      USER: "welder"
      GOOGLE_PROJECT: "${GOOGLE_PROJECT}"
      CLUSTER_NAME: "${CLUSTER_NAME}"
      OWNER_EMAIL: "${OWNER_EMAIL}"
    volumes:
      - rstudio-working:/data
    env_file:
      - /etc/google_application_credentials.env

volumes:
  rstudio-working:

