# Note: we need to stay on docker-compose version 2 because version 3 doesn't support
# configuring memory options in container mode. See discussion in:
# https://docs.docker.com/compose/compose-file/#resources
# https://github.com/docker/compose/issues/4513
version: '2'
services:
  welder:
    container_name: "${WELDER_SERVER_NAME}"
    image: "${WELDER_DOCKER_IMAGE}"
    # Override entrypoint with a placeholder to keep the container running indefinitely.
    # The cluster init script will start welder via docker exec,
    # when Application Default Credentials are available.
    # See https://broadworkbench.atlassian.net/browse/IA-1026
    entrypoint: "tail -f /dev/null"
    network_mode: host
    restart: always
    environment:
      # TODO what env vars are actually needed here?
      GOOGLE_PROJECT: "${GOOGLE_PROJECT}"
      STAGING_BUCKET: "${STAGING_BUCKET}"
      CLUSTER_NAME: "${CLUSTER_NAME}"
      OWNER_EMAIL: "${OWNER_EMAIL}"
    volumes:
      # shared with jupyter
      - /work:/work
    env_file:
      - /etc/google_application_credentials.env
    # See https://docs.docker.com/engine/reference/run/#user-memory-constraints
    mem_limit: 512m
    mem_reservation: 512m
    # disable swap by setting it to the same value as mem_limit
    memswap_limit: 512m

