'version: '3'
services:
  app:
    image: gcr.io/TEMPLATE_VAR_DOCKER_PROJECT/leonardo:TEMPLATE_VAR_DOCKER_TAG
    # dns: - 8.8.4.4
    # logging: {"driver": "syslog", "options": {"tag": "leonardo-app"}}
    volumes:
      - /home/ubuntu/app/jupyter-server.crt:/etc/jupyter-server.crt
      - /home/ubuntu/app/jupyter-server.key:/etc/jupyter-server.key
      - /home/ubuntu/app/leonardo.conf:/etc/leonardo.conf
      - /home/ubuntu/app/leonardo-account.pem:/etc/leonardo-account.pem:ro
      - /home/ubuntu/app/leo-client.p12:/etc/leo-client.p12
      - /home/ubuntu/app/rootCA.key:/etc/rootCA.key
      - /home/ubuntu/app/rootCA.pem:/etc/rootCA.pem
      - /etc/localtime:/etc/localtime:ro
      # Use the following volumes (and update appropriate JAVA_OPTS) if passing a mysql SSL key.
      #- /home/ubuntu/app/mysql.jks:/etc/ssl/leonardo.keystore:ro
      #- /home/ubuntu/app/mysql_trust.jks:/etc/ssl/leonardo.truststore:ro
    environment:
      # Unused java options:
      #-Djavax.net.ssl.keyStore=/etc/ssl/leonardo.keystore
      #-Djavax.net.ssl.keyStorePassword=xxxx
      #-Djavax.net.ssl.keyStoreType=pkcs12
      #-Djavax.net.ssl.trustStore=/etc/ssl/leonardo.truststore
      #-Djavax.net.ssl.trustStorePassword=xxxxx
      #-Djavax.net.ssl.trustStoreType=pkcs12
      JAVA_OPTS: -Dconfig.file=/etc/leonardo.conf
    links:
      - sqlproxy:sqlproxy

  userinterface:
      image: gcr.io/TEMPLATE_VAR_DOCKER_PROJECT/leonardo-ui:TEMPLATE_VAR_DOCKER_TAG
      environment:
        - FILTER_TO_CURRENT_USER=false
        - DEPLOY_ENVIRONMENT=prod
        - OAUTH_CLIENT_ID=TEMPLATE_VAR_OAUTH2_CLIENT_ID
        - DEFAULT_PROJECT=''
        - DISABLE_PROJECT_ENTRY=false
        - STARTUP_SCRIPT_URI=''
        - EXTRA_GOOGLE_SCOPES=''

  sqlproxy:
    image: gcr.io/cloudsql-docker/gce-proxy
    command:
      - /cloud_sql_proxy
      - -instances=TEMPLATE_VAR_SQL_INSTANCE_CONN=tcp:0.0.0.0:3306
    expose:
      - "3306"

  proxy:
    image: broadinstitute/openidc-proxy:latest
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:8888:8888"
    links:
      - app:app
      - userinterface:userinterface
    volumes:
      - /home/ubuntu/app/server.crt:/etc/ssl/certs/server.crt:ro
      - /home/ubuntu/app/server.key:/etc/ssl/private/server.key:ro
      - /home/ubuntu/app/ca-bundle.crt:/etc/ssl/certs/ca-bundle.crt:ro
      - /home/ubuntu/app/site.conf:/etc/apache2/sites-available/site.conf
    # logging: {"driver": "syslog", "options": {"tag": "leonardo-proxy"}}
    environment:
      # Configure auth proxy.
      CALLBACK_URI: https://TEMPLATE_VAR_DOMAIN/oauth2callback
      SERVER_NAME: TEMPLATE_VAR_DOMAIN
      LOG_LEVEL: warn
      AUTH_TYPE: AuthType oauth20
      AUTH_TYPE2: AuthType oauth20
      AUTH_REQUIRE: Require all granted
      REMOTE_USER_CLAIM: sub
      ENABLE_STACKDRIVER: 'yes'
      FILTER: AddOutputFilterByType DEFLATE application/json text/plain text/html application/javascript application/x-javascript
      FILTER2: AddOutputFilterByType DEFLATE application/json text/plain text/html application/javascript application/x-javascript
    restart: always
